### ISSUE TITLE
Make the library available in Maven Central

### ISSUE THREAD

**Issue by grofoli** [oliverselinger/failsafe-executor#8]
Please make the library available in Maven Central. For that you need to enhance your a pom.xml a little bit and create a ticket at Sonatype. 
Here are some links that might help you in that:
https://github.com/schmidrules/schmidrules/blob/master/pom.xml
https://blog.idrsolutions.com/2015/06/how-to-upload-your-java-artifact-to-maven-central/
Please note, that Schmidrules does not have a CI Pipeline set up, so you might want to include the deployment to sonatype probably in your ci pipeline as well.

**Comment by cinemast** [comment]
GitHub's packages might be simple step in between jitpack and maven central: https://github.com/oliverselinger/failsafe-executor/packages
